### ISSUE TITLE
type:"html"

### ISSUE THREAD

**Issue by Nashorn** [tc39/proposal-import-attributes#165]
Why not allow this?

**Comment by nicolo-ribaudo** [comment]
This proposal only defines the syntax space, but then the various attributes (such as `type: "json"`, or `type: "css"`) are defined elsewhere. Given that HTML is not a JS concept, probably the best place to discuss it would be https://github.com/whatwg/html/, which is also where `type: "css"` is defined.

However, please write an actual motivation for what you want it to behave like, and why you need it. You will need to convince two browser vendors that it's worth to implement it :)

**Comment by edbaafi** [comment]
@Nashorn - I couldn't find if you raised the issue elsewhere.  @nicolo-ribaudo - Thanks for the suggestion.  It seems there is a related (and still open) question from 2017 here: https://github.com/WICG/webcomponents/issues/645. I will raise this there.

re:
> actual motivation for what you want it to behave like, and why you need it.

This would align nicely with the current use case for [css module scripts](https://web.dev/articles/css-module-scripts).  Instead of constructing a CSSStyleSheet from the .css file, this should construct an [HTMLTemplateElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTemplateElement).  The imported template could be used like this:

```
import styleSheet from './custom-element.css' with {type: 'css'};
import template from './custom-element.html' with {type: 'html'};

export class CustomElement extends HTMLElement {

    #shadowRoot;

    constructor() {
        super();
        this.#shadowRoot = this.attachShadow({ mode: 'closed' });
        this.#shadowRoot.adoptedStyleSheets = [styleSheet];
        this.#shadowRoot.appendChild(template.content.cloneNode(true));
    }
}
```
