### ISSUE TITLE
Change keyword «with»

### ISSUE THREAD

**Issue by inoyakaigor** [tc39/proposal-import-attributes#3]
Keyword `with` already exists. Maybe better define MIME type like this:
`import module from 'module' as 'json'`?

**Comment by chicoxyzzy** [comment]
I don't see any problems with `with` in this context, it looks clean. Also `type` is sufficient part of syntax, it shouldn't be omitted. What I think about is if another option will be introduced, for example 
```js
const foo = import('module', { type: 'json', anotherOption: 42 })
```
How should static modules syntax look?
```js
import foo from 'module' with type 'json', otherOption 42; // ?
import foo from 'module' with type 'json', with otherOption 42; // ?
```
I'd prefer something like
```js
import foo from 'module' with { type: 'json', anotherOption: 42 }
```

**Comment by littledan** [comment]
An issue with `as` is that it's already part of import syntax, in a different position. `with` would be new and non-overlapping in this context. Anyway, I acknowledge that it's been pounded into everyone's head that `with` is bad, so maybe we should avoid it ....

**Comment by devsnek** [comment]
object syntax as xtuc posted is not possible because you'd have to evaluate a module to know if it shouldn't be evaluated.

**Comment by littledan** [comment]
@devsnek Yeah, that's what I'd imagine too. To me, the curly braces make me feel like you could use any expression there, which you can't.

**Comment by justinfagnani** [comment]
I'm proposing that `with` is reused for mixin application in: https://github.com/justinfagnani/proposal-mixins

Would this be too many separate meaning?

**Comment by chicoxyzzy** [comment]
in this statement
```js
import 'module' with type: 'json';
```
`'json'` looks like an expression too. What literal types should be allowed in `with`? Only strings and numbers?

**Comment by chicoxyzzy** [comment]
In the hypothetical situation with a bunch of options when the import string becomes too long curly brackets also look better IMHO
```js
import 'module' with
  type: 'json',
  anotherOption: 42,
  ...
  lastOption: 'hello' + 'world'; // should be allowed?
```
va
```js
import 'module' with {
  type: 'json',
  anotherOption: 42,
  ...
  lastOption: 'hello' + 'world', // should be allowed?
}
```

**Comment by devsnek** [comment]
the exact grammar should be entirely primitive literals

**Comment by chicoxyzzy** [comment]
so
```js
import 'module' with something: Symbol();
```
should be a valid grammar too?

**Comment by devsnek** [comment]
@chicoxyzzy that's not a primitive literal, that's a call expression.

**Comment by chicoxyzzy** [comment]
Oh, right. In that case, my only concern is that since `with` values are somewhat limited (could only be primitives), there is no big difference between
```js
import 'module' with
  type: 'json',
  anotherOption: 42n,
  ...
  lastOption: 'hello world';
```
and
```js
import 'module' with {
  type: 'json',
  anotherOption: 42n,
  ...
  lastOption: 'hello world',
};
```

Though curly braces option looks better and could allow trailing comma in case of a long list.

**Comment by chicoxyzzy** [comment]
Also those limitations look very close to `Can't convert Object with a non-const value` [from Tuples and Records proposal example](https://github.com/tc39/proposal-record-tuple#instantiation-and-converting-from-non-const-types) so perhaps some logic could be reused for `with` part of import statement

**Comment by chicoxyzzy** [comment]
Maybe even
```js
import 'module' with {|
  type: 'json',
  anotherOption: 42n,
  ...
  lastOption: 'hello world',
|};
```

**Comment by littledan** [comment]
Records also allow nested expressions in them, so they don't really get us any closer...

Literal strings which are not expressions in import statements is an established concept--that's what module specifiers are. They are sort of part of the bare minimum of what we need here to make the syntax work at all. So I'd suggest using literal strings and not other expression-like constructs.

**Comment by devsnek** [comment]
actually this gets me wondering about `import 'x#type=json'`. uses URLs, doesn't get sent to the server, backwards compat, etc.

**Comment by chicoxyzzy** [comment]
> Records also allow nested expressions in them, so they don't really get us any closer...

Disregard my proposal about `{| ... |}`. I meant that static semantics of imports and runtime semantics of records and tuples possibly can share some logic as an abstract operation, though both proposals are on very early stages to care about that.

**Comment by gibson042** [comment]
Overloading like that collides with the intended semantics of [URI fragment components](https://tools.ietf.org/html/rfc3986#section-3.5) ("_indirect identification of a secondary resource by reference to a primary resource and additional identifying information_").

**Comment by Janpot** [comment]
posted something [here](https://github.com/littledan/proposal-module-attributes/issues/12#issuecomment-551415311) but probably belongs here as well for completeness?

Parsing of the attributes could be left to hosts/compilers. For instance through querystring parsing.

```js
import json from "./foo.json" as "type=json&anotherOption=42";

// and default behavior
import json from "./foo.json" as "json";
// would be equivalent to
import json from "./foo.json" as "type=json";
```

**Comment by stevenvachon** [comment]
Yeah, `with` is bad. I think that we should use `eval` 😉

**Comment by stevenvachon** [comment]
> it's been pounded into everyone's head that `with` is bad, so maybe we should avoid it ....
Yeah, let's go with `eval` :wink:

**Comment by stevenvachon** [comment]
> it's been pounded into everyone's head that `with` is bad, so maybe we should avoid it ....

Yeah, let's go with `eval` :wink:

**Comment by ForsakenHarmony** [comment]
Have to say I agree with @chicoxyzzy

The `:` looks a bit weird on it's own, we don't have `from: './file'` either

And the first part `import { a, b, c } from ...` already kinda looks like an object

Currently if you have multiple attributes the syntax just gets a bit hard/confusing to read `import json from "./foo.json" with type: "json", thing: "bar";`

It's like an implicit "object"™

**Comment by thiagodp** [comment]
One [regret of the NodeJS's creator](https://jaxenter.com/ryan-dahl-fixing-node-deno-146190.html),  Ryan Dahl, was not [simplify the module loading](https://tinyclouds.org/jsconf2018.pdf) (see slides 16 and 23). That's why [Deno](https://deno.land/) supports `import` like this:
```javascript
import { serve } from "https://deno.land/std@v0.24.0/http/server.ts";
```
The URL syntax mitigates the problem of needing to have `node_modules`, for instance.

Whether the URL syntax gets popular, having URL parameters can make more sense:
```javascript
import products from "https://foo.bar/api/products/?type=json&anotherOption=42";
```

**Comment by ChoqueCastroLD** [comment]
Keyword should be more explicit than "with", a cleaner syntax may be "if" as we are using simple conditions to see if the module gets loaded  or not:

`import data from "./foo.json" if type: "json"`
`import "./bar.js" if type: "wasm"`

Multiple attributes should use curly braces like:

`import data from "./foo.json" if {type: "json", anotherOption: 10}`
`import "./bar.js" if {type: "module", anotherOption: 30}`

This allows for more options to be implemented in a not so far future.

**Comment by xlaywan** [comment]
We can use `when` keyword and explicit object. It will be similar to this proposal(with some restrictions) https://github.com/tc39/proposal-pattern-matching

```js
import foo from './foo.json' when {type: 'json'}
```
```js
import foo from './foo.json' when {type: 'json', anotherOption: 42}
```

**Comment by justinfagnani** [comment]
I don't think either `if`, or `when` or any word that implies the import is conditional should be used.

**Comment by ChoqueCastroLD** [comment]
@justinfagnani Could you explain a little bit more the reasoning behind your comment?

**Comment by justinfagnani** [comment]
Metadata may be used by the host for any purpose. The syntax shouldn't imply that the only purpose is to make the import conditional.

**Comment by hax** [comment]
`when`, `as` or any non-reserved words will add new ASI hazards:

```js
import foo from './foo.json'
when
{type: 'json'}
```

**Comment by ljharb** [comment]
We can add NLTH to solve that, but also, the committee has previous consensus not to let the creation of new ASI hazards block a feature (all else being equal).

**Comment by hax** [comment]
> the committee has previous consensus not to let the creation of new ASI hazards block a feature (all else being equal).

I have to declare again, as a TC39 delegate, I don't agree "previous consensus", if the new ASI hazards would cause significant cost in JS ecosystem.

**Comment by MylesBorins** [comment]
In this case would the lack of JSON, CSS, HTML, and WASM modules help to
deter the asi hazard concern? As it currently stands all are blocked
without this feature.

**Comment by littledan** [comment]
I think it'd be pretty weird to split up an import statement this way. You'd need *both* of the line breaks to have this ASI hazard. I don't think we're at the point where we should prohibit all NLTH. Of course, this feature is something that we'll seek consensus on individually, but I agree with [ljharb's understanding of history](https://github.com/tc39/proposal-module-attributes/issues/3#issuecomment-576518269) that we established when considering field declarations inside classes.

**Comment by Andrew-Cottrell** [comment]
Rather than base _type_ values on file extensions, it may be less surprising to use the assigned [Media Types](https://www.iana.org/assignments/media-types/media-types.xhtml)

    import foo from "./foo.css" with {type: "text/css"}
    import foo from "./foo.json" with {type: "application/json"}
    import foo from "./foo.wasm" with {type: "application/wasm"}

The default value for `type` would be `"application/javascript"` for compatibility with existing usage.

In a HTTP context there would be obvious correspondence between the `type` and the response's `Content-Type` header.

**Comment by xtuc** [comment]
We only mentionned the keyword `for` and  I would like to add `given`, for example:
```js
import a from "b" given {type: "json"}
import a from "b" given "json"
```

which, as a non native english speaker, can make sense?

**Comment by hax** [comment]
I prefer `for` or `with` because they are very simple words and already js keywords so no one will spell wrong. `having` and `given` are also simple words, but they are participles which may confuse some non-english speakers.

**Comment by littledan** [comment]
For Stage 2, I want to conclude that we'll use the key/value syntax. Over time, I haven't seen a better keyword than `with`, so I'd like to tentatively conclude that we'll use `with` keyword, but I'd be open to revisiting before Stage 3 if someone comes up with a keyword we can agree is better.

**Comment by xtuc** [comment]
Now that attributes need to be "check-only"  `if` would better reflects the current semantics.
But `if` isn't future proof because follow-up proposals might extended the semantics.

**Comment by ljharb** [comment]
@xtuc unless we wanted to have `if` for check-only attributes, and add `with` or something for different semantics:
```js
import result from 'path/to/module' if { type: 'json' } with { reviver: 'path/to/reviver/module };
```

**Comment by xtuc** [comment]
To be complete, I think it would play well with https://github.com/tc39/proposal-import-attributes/issues/56:
```js
import result from 'path/to/module' if { type: 'json' } fallback { alt: 'path/to/other-module' };
```

I think to make some visual sense the keywords would need to be ordered, which might not be a great UX. It seems also quite verbose to me.

**Comment by xtuc** [comment]
At this point, I think it makes sense to use the `if` keyword instead of `with` and I will send a PR to update the repo.

**Comment by matthewp** [comment]
As @justinfagnani mentioned using `if` indicates that the import is conditional, which it is not. I like @xtuc's suggestion of `given` here, but other similar synonyms can also work well.

**Comment by saschanaz** [comment]
#72 says it is indeed conditional. Is the behavior like that `import foo from "./abc.json" if { type: "json" }` is no-op when it's not JSON?

**Comment by littledan** [comment]
When it's not JSON, the module graph fails. The conditionality is about whether it should all fail or not.

**Comment by saschanaz** [comment]
`import ... if ...` sounds like a pythonic conditional statement, IMO it would be confusing if it still runs when if condition doesn't match 🤔

**Comment by littledan** [comment]
When the condition does not match, the module importing it fails to load. So, it's more of an assertion.

**Comment by Andrew-Cottrell** [comment]
Another option I haven't seen mentioned — prompted by the previous comment — is `assert`
```
import result from "path/to/module" assert { type: "json" }
```
In contrast to `if`, `assert` may more readily be understood to imply _throws-exception_ semantics rather than _no-op_ semantics.

**Comment by Andrew-Cottrell** [comment]
I dislike beating a dead horse, but I want to emphasise that, to some developers, `if` may imply (in magical pseudo-code)

    // import result from "path/to/module" if { type: "json" }
    var meta = [from "path/to/module"];
    if (meta.type === "json") {
        var result = meta.defaultExport;
    } else {
        // no-op and `result` has value `undefined` when the module code is evaluated
    }

While, for many developers, `assert` will imply a correct interpretation

    // import result from "path/to/module" assert { type: "json" }
    var meta = [from "path/to/module"];
    if (meta.type !== "json") {
        throw AssertionError(); // uncatchable exception and the module code is not evaluated
    }
    var result = meta.defaultExport;

**Comment by noinkling** [comment]
Just adding my opinion here (for what it's worth) to say that `if` feels unintuitive, and reads to me like Ruby's/Perl's "postfix" `if`, or Python's ternary or comprehension syntax, and I echo the sentiment that I would not intuitively expect an exception if the condition fails. `assert` would be much better in my opinion.

However, if I may push back further, `assert` still doesn't feel very intuitive in the simple JSON import case:

```
import foo from "./foo.json" assert { type: "json" };
```

At the end of the day, the motivation for the developer to use this feature (in this case) is because they want a file/resource interpreted by the engine/runtime as \<type\>. It therefore subverts expectations somewhat to have to say "*ensure* this file is \<type\>", because it doesn't inherently convey the sense (to me anyway) that they're asking the engine to change its interpretation behaviour (and if they weren't the extra syntax wouldn't be necessary anyway).

With that in mind, and noting that it doesn't seem like a good idea to compromise accurate semantics in the general case, would it be totally out of the question to make type, assuming it will be the most common application of this proposal, a special case in the interest of ergonomics? e.g:

```
import foo from "./foo.json" as "json" assert { ... }  // and whatever else
```

One of the reasons I bring this up is because I get the sense that if `assert`, or especially `if`, goes ahead, it's going to end up in a `globalThis` kind of situation with the wider community expressing dissatisfaction too late because it didn't enter their consciousness/they weren't made aware, especially since it was a recent change and there is a push for stage 3 scheduled in little over a week. Many (most?) people aware of this proposal still assume that `as` is the intended syntax (as did I until I happened upon the repo by chance today). This seems like the kind of thing that needs time for the updated proposal to disseminate and broader community input, which is why I felt compelled to speak up. I feel that at the very least the matter of ergonomics w.r.t. the keyword in the type case should be raised with the committee.

Just my 2c.

**Comment by Andrew-Cottrell** [comment]
> At the end of the day, the motivation for the developer to use this feature (in this case) is because they want a file/resource interpreted by the engine/runtime as &lt;type&gt;, regardless of what the exact semantics are (if that weren't true, the extra syntax wouldn't be necessary in the first place).  It therefore breaks expectations somewhat to have to say "_ensure_ this file is &lt;type&gt;", because it doesn't inherently convey the sense (to me anyway) that I'm asking the engine to change its interpretation behaviour.

I may have misunderstood, but I thought the engine/runtime is responsible for determining how to interpret the file/resource (e.g. via file extension or Content-Type header). Previously the proposed keyword was `as` or `with` in the expectation module attributes might also be used with non-assertion semantics. I believe the focus of the proposal changed — sometime before [3 June](https://github.com/tc39/notes/blob/master/meetings/2020-06/june-3.md#module-attributes-for-stage-2) — to only support assertion semantics. However, specifically for JSON modules the import condition (neé module attribute) was always intended as a security feature to assert an requirement. If the requirement for a "json" resource is not asserted then it need not be mentioned at all. From this point of view `as "json"` would not be useful to have in addition to `assert` or `if`.

```
// hope for the best, but may be unsafe/insecure if the resource has been replaced with JavaScript
import foo from "./foo"

// hope for the best, but module graph may fail to load if the resource has been replaced with JavaScript
import foo from "./foo" assert "json"
```

Please correct me if any aspect of my understanding is wrong or misleadingly incomplete.

**Comment by noinkling** [comment]
I'll try to explain better where I'm coming from. Here's a quote from the readme:

> Each JavaScript host is expected to provide a secondary way of checking whether a module is a JSON module. For example, on the Web, the MIME type would be checked to be a JSON MIME type. In "local" desktop/server/embedded environments, the file extension may be checked (possibly after symlinks are followed). The `type: "json"` is indicated at the import site, rather than only through that other mechanism in order to prevent the privilege escalation issue noted in the opening section.
> 
> Nevertheless, the interpretation of module loads with no conditions remains host/implementation-defined, so it is valid to implement JSON modules without requiring `if { type: "json" }`. It's just that `if { type: "json" }` must be supported everywhere. For example, it will be up to Node.js, not TC39, to decide whether import conditions are required or optional for JSON modules.

From my dumb, simplified, practical point of view this means:

- Without extra syntax = JSON imports maybe/probably won't work.
- With extra syntax = JSON imports will work.

Even though unsimplified it's more like (forgive me if I get something wrong):

- Without proposal syntax:
  - Without JSON media type/file extension: JSON imports won't work (not as JSON at the very least).
  - With JSON media type/file extension: JSON imports won't work on web, *maybe* in other environments.
- With proposal syntax:
  - Without JSON media type/file extension: JSON imports won't work.
  - With JSON media type/file extension: JSON imports will work.

This reveals that "extra syntax = JSON imports will work" isn't *necessarily* true, but my focus is not on the exceptional case - indeed I would *expect* that if there is some discrepancy with the source type (or any other easily detectable security vulnerability) an exception would be thrown; the keyword is almost irrelevant. One way I could maybe phrase this to get the point across is that the naming of `assert` (or `if`) derives from a relatively unimportant *implementation detail* of my (simpler, more practical) mental model.

Consider also that a dev is (generally) not going to be concerned if they included the extra syntax redundantly because the environment didn't require it, but they will obviously take note if they don't include the syntax and it *doesn't* work. In that situation, how can you help but associate capability with the syntax?

In essence, the `assert` keyword is technically/semantically appropriate, but derives from making a strong distinction between environment and the language proper. There is good reason to follow that principle, of course, but for a feature like this where the result ultimately relies on environment/implementation, I argue that there may be worthwhile advantage in adopting a more "holistic" keyword specifically for the type case, because `assert` and `if` feel disjointed in relation to how I believe people are going to most commonly think about and use this feature. `as` (or straight up `type`) is intuitive and reads nicely, and doesn't oppose the check semantics, just obscures them as an implementation detail.

> `as "json"` would not be useful to have in addition to `assert` or `if`

`as "<type>"` would replace `assert/if: { type: "<type>" }` and (presumably) keep the same semantics. I put the `assert` part in the example to represent any other potential (non-type) assertions, just because this proposal aims to make that case generalizable, but it can also represent any follow-up proposals like `with`/`fallback`/etc.

**Comment by Andrew-Cottrell** [comment]
My apologies for misunderstanding your point. I don't think `as` is suitable due to it already being used for a different purpose in `import` statements, but I think `type` could potentially be used in intuitive syntactic sugar dedicated to a common case.
```
import foo from "./foo" type "json";
```
could desugar to either
```
import foo from "./foo" if     { type: "json" };
import foo from "./foo" assert { type: "json" };
```
One drawback is some developers might incorrectly assume this syntactic sugar would be extended for other assertions that may be specified in future proposals.

**Comment by Andrew-Cottrell** [comment]
Although probably well known to others, it has just occurred to me `import` statements are very similar to SQL `select` statements.
```
import foo  as  f  from "./foos" if     { type: "json" };
select user as 'u' from  users   where  state = "active";
```
I don't know what proportion of JavaScript developers are familiar with SQL, but it _might_ be interesting to explore the parallels, between `import` and `select` statements, for the purpose of explaining import conditions to a wider audience.

This similarity suggests `where` as another alternative to `assert` or `if`.

**Comment by xtuc** [comment]
PR was merged, we are now using the `assert` keyword

**Comment by Alhadis** [comment]
Has `while` been considered?

~~~js
import foo from "source" while {type: "json"};
~~~

We already use the keyword in a similar context for `do… while` pairs, which is grammatically similar English:

~~~js
JavaScript: do { this } while { predicate };
English:   "do (this) for as long as (predicate) remains true."

JavaScript: import foo from "source" while { assertions };
English:   "import (foo) from (source) as long as (assertions) are all correct."
~~~

`assert` feels... weird, because it's a verb used in an imperative voice, the same as `import`. This kind of implies two actions are being taken: importing and asserting. Which basically boils down to:

~~~js
JavaScript: import foo from "source" assert { predicate };
English:   "import (foo) from source and assert that content
            we haven't even loaded yet satisfies (predicate)"
~~~

I'm probably just too attached to the idiomatic flow of our current syntax, which is currently well-formed English that reads quite nicely.

**Comment by ljharb** [comment]
To me, `while` implies a condition that will change.

**Comment by Alhadis** [comment]
Yeah, I know... 😞  Stupid English doesn't have a shorter way to write `expecting`:

~~~js
import foo from "source" expecting {type: "json"};
~~~

**Comment by ljharb** [comment]
`assert` is shorter :-p

**Comment by Alhadis** [comment]
Why is it necessary to use a keyword for something so specific? Moreover, how many other things (realistically) need asserting other than content-type?

**Comment by Alhadis** [comment]
Also, how many things—other than content-type—will realistically need asserting? [The proposal says](https://github.com/tc39/proposal-import-assertions/#:~:text=Assertions%20in%20addition%20than%20type%20may%20also%20be%20introduced%20for%20purposes%20not%20yet%20foreseen.):

> Assertions in addition than `type` may also be introduced for purposes not yet foreseen.

`assert` also doesn't help when a file is syntactically valid in more than one format. Consider:

~~~css
[true]
{
	content: "Bar";
}
~~~

What happens when `import("./contrived-example.css")` is used? The file is legal syntax in both CSS and JS (albeit fundamentally useless). Conversely, `as "css"` makes it clearer what the author's expectations are.

I doubt this problem will crop up today (especially with the small number of formats we're concerned with), but who knows what we might be `import`ing in another 10 years' time...

**Comment by littledan** [comment]
@Alhadis Well, the semantics *are* to assert that the content satisfies the predicate. This makes me glad you have this interpretation.

**Comment by dtinth** [comment]
I saw a few other languages use the -ing form of verb to modify import statements, so I am surprised that the keyword “`asserting`” has not been brought up so far.

Examples from other languages:

- Haskell (`hiding`): `import Prelude hiding (zip)`
- Elm (`exposing`): `import Post exposing (Post, estimatedReadTime)`

**Comment by nicolo-ribaudo** [comment]
After some back and forth, and after almost settling on `assert`, the proposal has been updated to the following syntax:
```js
import { x } from "foo" with { attributeKey: "attributeValue" }
```

Thanks everyone for taking part in the discussion!
