### ISSUE TITLE
Access attributes by import.meta?

### ISSUE THREAD

**Issue by Jack-Works** [tc39/proposal-import-attributes#58]
A.js

```js
import './b.js' with {a: 1}
```

B.js
```js
console.log(import.meta.attributes.a) // 1
```

**Comment by ljharb** [comment]
B could be imported many times with different metadata, and it’s only evaluated once, the first time. it wouldn’t make much sense to me for it to have access only to the metadata provided by the first importer.

**Comment by MylesBorins** [comment]
I think this would depend on the caching model.

If there was an attribute such as "meta" that was part of the key for the
cache this could effectively make different instances

**Comment by ljharb** [comment]
Sure, but then the importer is forcing the module to be re-evaluated again in a way the author may not have intended. For example, if my web server rejects any query strings and only allows a single URL, then you can’t invalidate that cache and evaluate it twice on the same page (afaik). Giving the importer runtime cache control seems concerning; are there any other examples in the web platform where this is the case? In node it can be done, but anyone would assume they’re risking voiding their warranty by doing that - i don’t think the same would apply if it was first class syntax.

**Comment by littledan** [comment]
My inclination right now is to leave both things--the interpretation of unknown attributes, and the set of `import.meta` properties--up to the host. Is "leaving it up to the host" an acceptable path for this decision, or do we need to make a requirement on hosts about `import.meta` here?

I agree with others here that this is only acceptable if these unknown attributes are considered part of the cache key; this shouldn't be a contest about who imports first. The current draft spec text *does* permit hosts to use module attributes as part of the cache key (though not `type`, which is required to just be a check). If I were to design a host, here's an ordered list of my preferences, from most preferred to least, when it comes to these aspects:
- Most preferred: Reject unknown module attributes, to ensure maximum future-proofing for flexibly adding interpretations later
- Middle: Ignore unknown module attributes, but use the same copy of the module. This implies that `import.meta.attributes` cannot be exposed.
- Least preferred: Ignore module attributes and generate a separate copy of the module, just so that `import.meta.attributes` is different. It's hard for me to imagine when you'd actually want this cost tradeoff. Maybe use cases would push it up in my personal host-designer calculation.

@xtuc has previously suggested that we expose this kind of thing through `import.meta`, but I didn't think it through as much as now.

**Comment by nicolo-ribaudo** [comment]
The proposal allow hosts to expose attributes on `import.meta`, however there are currently no plans in known hosts (HTML, WinterCG hosts) to expose them.
